const SurahActionTypes={
    LOAD_SURAH_LIST_START:'LOAD_SURAH_LIST_START',
    LOAD_SURAH_LIST_SUCCESS:'LOAD_SURAH_LIST_SUCCESS',
    LOAD_SURAH_LIST_FAILURE:'LOAD_SURAH_LIST_FAILURE',
    CHANGE_SURAH_START:'CHANGE_SURAH_START',
    LOAD_SURAH_START:'LOAD_SURAH_START',
    LOAD_SURAH_SUCCESS:'LOAD_SURAH_SUCCESS',
    LOAD_SURAH_FAILURE:'LOAD_SURAH_FAILURE',
    FONT_FACE_LOAD: 'FONT_FACE_LOAD',
    FONT_FACE_SUCCESS : 'FONT_FACE_SUCCESS',
    FONT_FACE_FAILURE : 'FONT_FACE_FAILURE',
   };
   export default SurahActionTypes;